/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TenantDomainCheckResponse,
  TenantDomainCreateRequest,
  TenantDomainCreateResponse,
  TenantDomainDetailResponse,
  TenantDomainsResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TenantDomainCheckResponseFromJSON,
    TenantDomainCheckResponseToJSON,
    TenantDomainCreateRequestFromJSON,
    TenantDomainCreateRequestToJSON,
    TenantDomainCreateResponseFromJSON,
    TenantDomainCreateResponseToJSON,
    TenantDomainDetailResponseFromJSON,
    TenantDomainDetailResponseToJSON,
    TenantDomainsResponseFromJSON,
    TenantDomainsResponseToJSON,
} from '../models/index';

export interface CheckTenantDomainRequest {
    domain: string;
}

export interface CreateTenantDomainRequest {
    tenantDomainCreateRequest: TenantDomainCreateRequest;
}

export interface GetTenantDomainRequest {
    domain: string;
}

/**
 * 
 */
export class DomainsApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkTenantDomain without sending the request
     */
    async checkTenantDomainRequestOpts(requestParameters: CheckTenantDomainRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling checkTenantDomain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/domains/{domain}/check`;
        urlPath = urlPath.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters['domain'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Re-checks the verification status of a tenant domain and returns the latest provider verification state.
     * Check tenant domain verification
     */
    async checkTenantDomainRaw(requestParameters: CheckTenantDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDomainCheckResponse>> {
        const requestOptions = await this.checkTenantDomainRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDomainCheckResponseFromJSON(jsonValue));
    }

    /**
     * Re-checks the verification status of a tenant domain and returns the latest provider verification state.
     * Check tenant domain verification
     */
    async checkTenantDomain(requestParameters: CheckTenantDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDomainCheckResponse> {
        const response = await this.checkTenantDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTenantDomain without sending the request
     */
    async createTenantDomainRequestOpts(requestParameters: CreateTenantDomainRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantDomainCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'tenantDomainCreateRequest',
                'Required parameter "tenantDomainCreateRequest" was null or undefined when calling createTenantDomain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/domains`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TenantDomainCreateRequestToJSON(requestParameters['tenantDomainCreateRequest']),
        };
    }

    /**
     * Registers a domain for the authenticated tenant and begins the verification process.
     * Add tenant domain
     */
    async createTenantDomainRaw(requestParameters: CreateTenantDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDomainCreateResponse>> {
        const requestOptions = await this.createTenantDomainRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDomainCreateResponseFromJSON(jsonValue));
    }

    /**
     * Registers a domain for the authenticated tenant and begins the verification process.
     * Add tenant domain
     */
    async createTenantDomain(requestParameters: CreateTenantDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDomainCreateResponse> {
        const response = await this.createTenantDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTenantDomain without sending the request
     */
    async getTenantDomainRequestOpts(requestParameters: GetTenantDomainRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling getTenantDomain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/domains/{domain}`;
        urlPath = urlPath.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters['domain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns details for a tenant domain, including SES verification status and required DNS records.
     * Get tenant domain details
     */
    async getTenantDomainRaw(requestParameters: GetTenantDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDomainDetailResponse>> {
        const requestOptions = await this.getTenantDomainRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDomainDetailResponseFromJSON(jsonValue));
    }

    /**
     * Returns details for a tenant domain, including SES verification status and required DNS records.
     * Get tenant domain details
     */
    async getTenantDomain(requestParameters: GetTenantDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDomainDetailResponse> {
        const response = await this.getTenantDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTenantDomains without sending the request
     */
    async listTenantDomainsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/domains`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the domains registered for the authenticated tenant.
     * List tenant domains
     */
    async listTenantDomainsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDomainsResponse>> {
        const requestOptions = await this.listTenantDomainsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDomainsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the domains registered for the authenticated tenant.
     * List tenant domains
     */
    async listTenantDomains(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDomainsResponse> {
        const response = await this.listTenantDomainsRaw(initOverrides);
        return await response.value();
    }

}
