/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  MessageStatusResponse,
  SendEmailRequest,
  SendEmailResponse,
  TenantMessageEventsResponse,
  TenantMessageResponse,
  TenantMessagesResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MessageStatusResponseFromJSON,
    MessageStatusResponseToJSON,
    SendEmailRequestFromJSON,
    SendEmailRequestToJSON,
    SendEmailResponseFromJSON,
    SendEmailResponseToJSON,
    TenantMessageEventsResponseFromJSON,
    TenantMessageEventsResponseToJSON,
    TenantMessageResponseFromJSON,
    TenantMessageResponseToJSON,
    TenantMessagesResponseFromJSON,
    TenantMessagesResponseToJSON,
} from '../models/index';

export interface GetMessageStatusRequest {
    messageId: string;
}

export interface GetTenantMessageRequest {
    messageId: string;
}

export interface ListTenantMessageEventsRequest {
    messageId: string;
    cursor?: string;
    limit?: number;
}

export interface ListTenantMessagesRequest {
    cursor?: string;
    limit?: number;
}

export interface SendEmailOperationRequest {
    sendEmailRequest: SendEmailRequest;
}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMessageStatus without sending the request
     */
    async getMessageStatusRequestOpts(requestParameters: GetMessageStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling getMessageStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/status/{messageId}`;
        urlPath = urlPath.replace(`{${"messageId"}}`, encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current delivery status for a message.
     * Get message delivery status
     */
    async getMessageStatusRaw(requestParameters: GetMessageStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageStatusResponse>> {
        const requestOptions = await this.getMessageStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageStatusResponseFromJSON(jsonValue));
    }

    /**
     * Returns the current delivery status for a message.
     * Get message delivery status
     */
    async getMessageStatus(requestParameters: GetMessageStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageStatusResponse> {
        const response = await this.getMessageStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTenantMessage without sending the request
     */
    async getTenantMessageRequestOpts(requestParameters: GetTenantMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling getTenantMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/messages/{messageId}`;
        urlPath = urlPath.replace(`{${"messageId"}}`, encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single message record for the authenticated tenant.
     * Get tenant message
     */
    async getTenantMessageRaw(requestParameters: GetTenantMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantMessageResponse>> {
        const requestOptions = await this.getTenantMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantMessageResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single message record for the authenticated tenant.
     * Get tenant message
     */
    async getTenantMessage(requestParameters: GetTenantMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantMessageResponse> {
        const response = await this.getTenantMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTenantMessageEvents without sending the request
     */
    async listTenantMessageEventsRequestOpts(requestParameters: ListTenantMessageEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling listTenantMessageEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/messages/{messageId}/events`;
        urlPath = urlPath.replace(`{${"messageId"}}`, encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the event timeline for a single tenant message, including internal processing events and provider delivery events.
     * List tenant message events
     */
    async listTenantMessageEventsRaw(requestParameters: ListTenantMessageEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantMessageEventsResponse>> {
        const requestOptions = await this.listTenantMessageEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantMessageEventsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the event timeline for a single tenant message, including internal processing events and provider delivery events.
     * List tenant message events
     */
    async listTenantMessageEvents(requestParameters: ListTenantMessageEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantMessageEventsResponse> {
        const response = await this.listTenantMessageEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTenantMessages without sending the request
     */
    async listTenantMessagesRequestOpts(requestParameters: ListTenantMessagesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/messages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns paginated message logs for the authenticated tenant.
     * List tenant messages
     */
    async listTenantMessagesRaw(requestParameters: ListTenantMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantMessagesResponse>> {
        const requestOptions = await this.listTenantMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantMessagesResponseFromJSON(jsonValue));
    }

    /**
     * Returns paginated message logs for the authenticated tenant.
     * List tenant messages
     */
    async listTenantMessages(requestParameters: ListTenantMessagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantMessagesResponse> {
        const response = await this.listTenantMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmail without sending the request
     */
    async sendEmailRequestOpts(requestParameters: SendEmailOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'sendEmailRequest',
                'Required parameter "sendEmailRequest" was null or undefined when calling sendEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendEmailRequestToJSON(requestParameters['sendEmailRequest']),
        };
    }

    /**
     * Queue a transactional email for delivery.
     * Send an email
     */
    async sendEmailRaw(requestParameters: SendEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendEmailResponse>> {
        const requestOptions = await this.sendEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendEmailResponseFromJSON(jsonValue));
    }

    /**
     * Queue a transactional email for delivery.
     * Send an email
     */
    async sendEmail(requestParameters: SendEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendEmailResponse> {
        const response = await this.sendEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
