/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TenantPoliciesAcceptResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TenantPoliciesAcceptResponseFromJSON,
    TenantPoliciesAcceptResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TenantApi extends runtime.BaseAPI {

    /**
     * Creates request options for acceptTenantPolicies without sending the request
     */
    async acceptTenantPoliciesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/tenant/policies/accept`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Records acceptance of the current required policy version for the authenticated tenant.
     * Accept tenant policies
     */
    async acceptTenantPoliciesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantPoliciesAcceptResponse>> {
        const requestOptions = await this.acceptTenantPoliciesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantPoliciesAcceptResponseFromJSON(jsonValue));
    }

    /**
     * Records acceptance of the current required policy version for the authenticated tenant.
     * Accept tenant policies
     */
    async acceptTenantPolicies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantPoliciesAcceptResponse> {
        const response = await this.acceptTenantPoliciesRaw(initOverrides);
        return await response.value();
    }

}
