/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CallerTypeEnum = {
    Public: 'public',
    Smtp: 'smtp',
    Admin: 'admin'
} as const;
export type CallerTypeEnum = typeof CallerTypeEnum[keyof typeof CallerTypeEnum];


export function instanceOfCallerTypeEnum(value: any): boolean {
    for (const key in CallerTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(CallerTypeEnum, key)) {
            if (CallerTypeEnum[key as keyof typeof CallerTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CallerTypeEnumFromJSON(json: any): CallerTypeEnum {
    return CallerTypeEnumFromJSONTyped(json, false);
}

export function CallerTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallerTypeEnum {
    return json as CallerTypeEnum;
}

export function CallerTypeEnumToJSON(value?: CallerTypeEnum | null): any {
    return value as any;
}

export function CallerTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CallerTypeEnum {
    return value as CallerTypeEnum;
}

