/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DnsRecordTypeEnum = {
    Cname: 'CNAME',
    Mx: 'MX',
    Txt: 'TXT'
} as const;
export type DnsRecordTypeEnum = typeof DnsRecordTypeEnum[keyof typeof DnsRecordTypeEnum];


export function instanceOfDnsRecordTypeEnum(value: any): boolean {
    for (const key in DnsRecordTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(DnsRecordTypeEnum, key)) {
            if (DnsRecordTypeEnum[key as keyof typeof DnsRecordTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DnsRecordTypeEnumFromJSON(json: any): DnsRecordTypeEnum {
    return DnsRecordTypeEnumFromJSONTyped(json, false);
}

export function DnsRecordTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsRecordTypeEnum {
    return json as DnsRecordTypeEnum;
}

export function DnsRecordTypeEnumToJSON(value?: DnsRecordTypeEnum | null): any {
    return value as any;
}

export function DnsRecordTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DnsRecordTypeEnum {
    return value as DnsRecordTypeEnum;
}

