/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainStatusEnum = {
    Pending: 'PENDING',
    Verified: 'VERIFIED'
} as const;
export type DomainStatusEnum = typeof DomainStatusEnum[keyof typeof DomainStatusEnum];


export function instanceOfDomainStatusEnum(value: any): boolean {
    for (const key in DomainStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(DomainStatusEnum, key)) {
            if (DomainStatusEnum[key as keyof typeof DomainStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainStatusEnumFromJSON(json: any): DomainStatusEnum {
    return DomainStatusEnumFromJSONTyped(json, false);
}

export function DomainStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainStatusEnum {
    return json as DomainStatusEnum;
}

export function DomainStatusEnumToJSON(value?: DomainStatusEnum | null): any {
    return value as any;
}

export function DomainStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainStatusEnum {
    return value as DomainStatusEnum;
}

