/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ErrorCode = {
    BadRequest: 'BAD_REQUEST',
    Unauthorized: 'UNAUTHORIZED',
    Forbidden: 'FORBIDDEN',
    NotFound: 'NOT_FOUND',
    ValidationError: 'VALIDATION_ERROR',
    Conflict: 'CONFLICT',
    PayloadTooLarge: 'PAYLOAD_TOO_LARGE',
    ServiceUnavailable: 'SERVICE_UNAVAILABLE',
    DomainNotVerified: 'DOMAIN_NOT_VERIFIED',
    SendingNotEnabled: 'SENDING_NOT_ENABLED',
    PolicyNotAccepted: 'POLICY_NOT_ACCEPTED'
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export function instanceOfErrorCode(value: any): boolean {
    for (const key in ErrorCode) {
        if (Object.prototype.hasOwnProperty.call(ErrorCode, key)) {
            if (ErrorCode[key as keyof typeof ErrorCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

export function ErrorCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): ErrorCode {
    return value as ErrorCode;
}

