/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
    ErrorCodeToJSONTyped,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface ErrorBody
 */
export interface ErrorBody {
    /**
     * 
     * @type {ErrorCode}
     * @memberof ErrorBody
     */
    code: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    message: string;
    /**
     * Optional field-level validation errors
     * @type {{ [key: string]: any; }}
     * @memberof ErrorBody
     */
    fields?: { [key: string]: any; };
}



/**
 * Check if a given object implements the ErrorBody interface.
 */
export function instanceOfErrorBody(value: object): value is ErrorBody {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorBodyFromJSON(json: any): ErrorBody {
    return ErrorBodyFromJSONTyped(json, false);
}

export function ErrorBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBody {
    if (json == null) {
        return json;
    }
    return {
        
        'code': ErrorCodeFromJSON(json['code']),
        'message': json['message'],
        'fields': json['fields'] == null ? undefined : json['fields'],
    };
}

export function ErrorBodyToJSON(json: any): ErrorBody {
    return ErrorBodyToJSONTyped(json, false);
}

export function ErrorBodyToJSONTyped(value?: ErrorBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ErrorCodeToJSON(value['code']),
        'message': value['message'],
        'fields': value['fields'],
    };
}

