/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventGroupEnum = {
    Internal: 'internal',
    Engagement: 'engagement'
} as const;
export type EventGroupEnum = typeof EventGroupEnum[keyof typeof EventGroupEnum];


export function instanceOfEventGroupEnum(value: any): boolean {
    for (const key in EventGroupEnum) {
        if (Object.prototype.hasOwnProperty.call(EventGroupEnum, key)) {
            if (EventGroupEnum[key as keyof typeof EventGroupEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventGroupEnumFromJSON(json: any): EventGroupEnum {
    return EventGroupEnumFromJSONTyped(json, false);
}

export function EventGroupEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventGroupEnum {
    return json as EventGroupEnum;
}

export function EventGroupEnumToJSON(value?: EventGroupEnum | null): any {
    return value as any;
}

export function EventGroupEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): EventGroupEnum {
    return value as EventGroupEnum;
}

