/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageStatusEnum } from './MessageStatusEnum';
import {
    MessageStatusEnumFromJSON,
    MessageStatusEnumFromJSONTyped,
    MessageStatusEnumToJSON,
    MessageStatusEnumToJSONTyped,
} from './MessageStatusEnum';

/**
 * 
 * @export
 * @interface MessageStatus
 */
export interface MessageStatus {
    /**
     * 
     * @type {string}
     * @memberof MessageStatus
     */
    messageId: string;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof MessageStatus
     */
    status: MessageStatusEnum;
    /**
     * Optional reason for failure, bounce, complaint, or rejection
     * @type {string}
     * @memberof MessageStatus
     */
    reason: string | null;
    /**
     * Unix timestamp in seconds
     * @type {number}
     * @memberof MessageStatus
     */
    createdAt: number;
    /**
     * Unix timestamp in seconds
     * @type {number}
     * @memberof MessageStatus
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof MessageStatus
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof MessageStatus
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof MessageStatus
     */
    subject: string;
    /**
     * Provider message identifier
     * @type {string}
     * @memberof MessageStatus
     */
    sendingMessageId: string;
}



/**
 * Check if a given object implements the MessageStatus interface.
 */
export function instanceOfMessageStatus(value: object): value is MessageStatus {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('sendingMessageId' in value) || value['sendingMessageId'] === undefined) return false;
    return true;
}

export function MessageStatusFromJSON(json: any): MessageStatus {
    return MessageStatusFromJSONTyped(json, false);
}

export function MessageStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'],
        'status': MessageStatusEnumFromJSON(json['status']),
        'reason': json['reason'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'to': json['to'],
        'from': json['from'],
        'subject': json['subject'],
        'sendingMessageId': json['sendingMessageId'],
    };
}

export function MessageStatusToJSON(json: any): MessageStatus {
    return MessageStatusToJSONTyped(json, false);
}

export function MessageStatusToJSONTyped(value?: MessageStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
        'status': MessageStatusEnumToJSON(value['status']),
        'reason': value['reason'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'to': value['to'],
        'from': value['from'],
        'subject': value['subject'],
        'sendingMessageId': value['sendingMessageId'],
    };
}

