/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageStatus } from './MessageStatus';
import {
    MessageStatusFromJSON,
    MessageStatusFromJSONTyped,
    MessageStatusToJSON,
    MessageStatusToJSONTyped,
} from './MessageStatus';

/**
 * 
 * @export
 * @interface MessageStatusResponse
 */
export interface MessageStatusResponse {
    /**
     * 
     * @type {MessageStatus}
     * @memberof MessageStatusResponse
     */
    data: MessageStatus;
}

/**
 * Check if a given object implements the MessageStatusResponse interface.
 */
export function instanceOfMessageStatusResponse(value: object): value is MessageStatusResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MessageStatusResponseFromJSON(json: any): MessageStatusResponse {
    return MessageStatusResponseFromJSONTyped(json, false);
}

export function MessageStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': MessageStatusFromJSON(json['data']),
    };
}

export function MessageStatusResponseToJSON(json: any): MessageStatusResponse {
    return MessageStatusResponseToJSONTyped(json, false);
}

export function MessageStatusResponseToJSONTyped(value?: MessageStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MessageStatusToJSON(value['data']),
    };
}

