/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MessageStatusEnum = {
    Accepted: 'ACCEPTED',
    Queued: 'QUEUED',
    Sending: 'SENDING',
    Sent: 'SENT',
    Delivered: 'DELIVERED',
    Failed: 'FAILED',
    Rejected: 'REJECTED',
    Bounced: 'BOUNCED',
    Complaint: 'COMPLAINT'
} as const;
export type MessageStatusEnum = typeof MessageStatusEnum[keyof typeof MessageStatusEnum];


export function instanceOfMessageStatusEnum(value: any): boolean {
    for (const key in MessageStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(MessageStatusEnum, key)) {
            if (MessageStatusEnum[key as keyof typeof MessageStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MessageStatusEnumFromJSON(json: any): MessageStatusEnum {
    return MessageStatusEnumFromJSONTyped(json, false);
}

export function MessageStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageStatusEnum {
    return json as MessageStatusEnum;
}

export function MessageStatusEnumToJSON(value?: MessageStatusEnum | null): any {
    return value as any;
}

export function MessageStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MessageStatusEnum {
    return value as MessageStatusEnum;
}

