/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProviderEventTypeEnum = {
    Send: 'Send',
    Delivery: 'Delivery',
    Bounce: 'Bounce',
    Complaint: 'Complaint',
    Open: 'Open',
    Click: 'Click',
    Reject: 'Reject',
    RenderingFailure: 'RenderingFailure',
    DeliveryDelay: 'DeliveryDelay',
    Subscription: 'Subscription'
} as const;
export type ProviderEventTypeEnum = typeof ProviderEventTypeEnum[keyof typeof ProviderEventTypeEnum];


export function instanceOfProviderEventTypeEnum(value: any): boolean {
    for (const key in ProviderEventTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(ProviderEventTypeEnum, key)) {
            if (ProviderEventTypeEnum[key as keyof typeof ProviderEventTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProviderEventTypeEnumFromJSON(json: any): ProviderEventTypeEnum {
    return ProviderEventTypeEnumFromJSONTyped(json, false);
}

export function ProviderEventTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderEventTypeEnum {
    return json as ProviderEventTypeEnum;
}

export function ProviderEventTypeEnumToJSON(value?: ProviderEventTypeEnum | null): any {
    return value as any;
}

export function ProviderEventTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ProviderEventTypeEnum {
    return value as ProviderEventTypeEnum;
}

