/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProviderEnum = {
    Ses: 'SES'
} as const;
export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];


export function instanceOfProviderEnum(value: any): boolean {
    for (const key in ProviderEnum) {
        if (Object.prototype.hasOwnProperty.call(ProviderEnum, key)) {
            if (ProviderEnum[key as keyof typeof ProviderEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProviderEnumFromJSON(json: any): ProviderEnum {
    return ProviderEnumFromJSONTyped(json, false);
}

export function ProviderEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderEnum {
    return json as ProviderEnum;
}

export function ProviderEnumToJSON(value?: ProviderEnum | null): any {
    return value as any;
}

export function ProviderEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ProviderEnum {
    return value as ProviderEnum;
}

