/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageStatusEnum } from './MessageStatusEnum';
import {
    MessageStatusEnumFromJSON,
    MessageStatusEnumFromJSONTyped,
    MessageStatusEnumToJSON,
    MessageStatusEnumToJSONTyped,
} from './MessageStatusEnum';

/**
 * 
 * @export
 * @interface SendEmailResult
 */
export interface SendEmailResult {
    /**
     * 
     * @type {string}
     * @memberof SendEmailResult
     */
    messageId: string;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof SendEmailResult
     */
    status: MessageStatusEnum;
}



/**
 * Check if a given object implements the SendEmailResult interface.
 */
export function instanceOfSendEmailResult(value: object): value is SendEmailResult {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SendEmailResultFromJSON(json: any): SendEmailResult {
    return SendEmailResultFromJSONTyped(json, false);
}

export function SendEmailResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailResult {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'],
        'status': MessageStatusEnumFromJSON(json['status']),
    };
}

export function SendEmailResultToJSON(json: any): SendEmailResult {
    return SendEmailResultToJSONTyped(json, false);
}

export function SendEmailResultToJSONTyped(value?: SendEmailResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
        'status': MessageStatusEnumToJSON(value['status']),
    };
}

