/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailRequest
 */
export interface SendEmailRequest {
    /**
     * Sender in RFC 5322 mailbox format
     * @type {string}
     * @memberof SendEmailRequest
     */
    from: string;
    /**
     * Recipient email address
     * @type {string}
     * @memberof SendEmailRequest
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailRequest
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailRequest
     */
    html?: string;
    /**
     * Optional message tags
     * @type {{ [key: string]: string; }}
     * @memberof SendEmailRequest
     */
    tags?: { [key: string]: string; };
}

/**
 * Check if a given object implements the SendEmailRequest interface.
 */
export function instanceOfSendEmailRequest(value: object): value is SendEmailRequest {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function SendEmailRequestFromJSON(json: any): SendEmailRequest {
    return SendEmailRequestFromJSONTyped(json, false);
}

export function SendEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'subject': json['subject'],
        'text': json['text'] == null ? undefined : json['text'],
        'html': json['html'] == null ? undefined : json['html'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function SendEmailRequestToJSON(json: any): SendEmailRequest {
    return SendEmailRequestToJSONTyped(json, false);
}

export function SendEmailRequestToJSONTyped(value?: SendEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
        'subject': value['subject'],
        'text': value['text'],
        'html': value['html'],
        'tags': value['tags'],
    };
}

