/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendEmailResult } from './SendEmailResult';
import {
    SendEmailResultFromJSON,
    SendEmailResultFromJSONTyped,
    SendEmailResultToJSON,
    SendEmailResultToJSONTyped,
} from './SendEmailResult';

/**
 * 
 * @export
 * @interface SendEmailResponse
 */
export interface SendEmailResponse {
    /**
     * 
     * @type {SendEmailResult}
     * @memberof SendEmailResponse
     */
    data: SendEmailResult;
}

/**
 * Check if a given object implements the SendEmailResponse interface.
 */
export function instanceOfSendEmailResponse(value: object): value is SendEmailResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SendEmailResponseFromJSON(json: any): SendEmailResponse {
    return SendEmailResponseFromJSONTyped(json, false);
}

export function SendEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SendEmailResultFromJSON(json['data']),
    };
}

export function SendEmailResponseToJSON(json: any): SendEmailResponse {
    return SendEmailResponseToJSONTyped(json, false);
}

export function SendEmailResponseToJSONTyped(value?: SendEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SendEmailResultToJSON(value['data']),
    };
}

