/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SesVerificationStatusEnum = {
    Pending: 'PENDING',
    Success: 'SUCCESS',
    Failed: 'FAILED',
    TemporaryFailure: 'TEMPORARY_FAILURE'
} as const;
export type SesVerificationStatusEnum = typeof SesVerificationStatusEnum[keyof typeof SesVerificationStatusEnum];


export function instanceOfSesVerificationStatusEnum(value: any): boolean {
    for (const key in SesVerificationStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(SesVerificationStatusEnum, key)) {
            if (SesVerificationStatusEnum[key as keyof typeof SesVerificationStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SesVerificationStatusEnumFromJSON(json: any): SesVerificationStatusEnum {
    return SesVerificationStatusEnumFromJSONTyped(json, false);
}

export function SesVerificationStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SesVerificationStatusEnum {
    return json as SesVerificationStatusEnum;
}

export function SesVerificationStatusEnumToJSON(value?: SesVerificationStatusEnum | null): any {
    return value as any;
}

export function SesVerificationStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SesVerificationStatusEnum {
    return value as SesVerificationStatusEnum;
}

