/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SourceEnum = {
    Api: 'api',
    Worker: 'worker',
    Sns: 'sns',
    Provider: 'provider'
} as const;
export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];


export function instanceOfSourceEnum(value: any): boolean {
    for (const key in SourceEnum) {
        if (Object.prototype.hasOwnProperty.call(SourceEnum, key)) {
            if (SourceEnum[key as keyof typeof SourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SourceEnumFromJSON(json: any): SourceEnum {
    return SourceEnumFromJSONTyped(json, false);
}

export function SourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceEnum {
    return json as SourceEnum;
}

export function SourceEnumToJSON(value?: SourceEnum | null): any {
    return value as any;
}

export function SourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SourceEnum {
    return value as SourceEnum;
}

