/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StageEnum = {
    Dev: 'dev',
    Prod: 'prod'
} as const;
export type StageEnum = typeof StageEnum[keyof typeof StageEnum];


export function instanceOfStageEnum(value: any): boolean {
    for (const key in StageEnum) {
        if (Object.prototype.hasOwnProperty.call(StageEnum, key)) {
            if (StageEnum[key as keyof typeof StageEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StageEnumFromJSON(json: any): StageEnum {
    return StageEnumFromJSONTyped(json, false);
}

export function StageEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageEnum {
    return json as StageEnum;
}

export function StageEnumToJSON(value?: StageEnum | null): any {
    return value as any;
}

export function StageEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): StageEnum {
    return value as StageEnum;
}

