/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDomainDetail } from './TenantDomainDetail';
import {
    TenantDomainDetailFromJSON,
    TenantDomainDetailFromJSONTyped,
    TenantDomainDetailToJSON,
    TenantDomainDetailToJSONTyped,
} from './TenantDomainDetail';

/**
 * 
 * @export
 * @interface TenantDomainDetailResponse
 */
export interface TenantDomainDetailResponse {
    /**
     * 
     * @type {TenantDomainDetail}
     * @memberof TenantDomainDetailResponse
     */
    data: TenantDomainDetail;
}

/**
 * Check if a given object implements the TenantDomainDetailResponse interface.
 */
export function instanceOfTenantDomainDetailResponse(value: object): value is TenantDomainDetailResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantDomainDetailResponseFromJSON(json: any): TenantDomainDetailResponse {
    return TenantDomainDetailResponseFromJSONTyped(json, false);
}

export function TenantDomainDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantDomainDetailFromJSON(json['data']),
    };
}

export function TenantDomainDetailResponseToJSON(json: any): TenantDomainDetailResponse {
    return TenantDomainDetailResponseToJSONTyped(json, false);
}

export function TenantDomainDetailResponseToJSONTyped(value?: TenantDomainDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantDomainDetailToJSON(value['data']),
    };
}

