/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantPoliciesAccept
 */
export interface TenantPoliciesAccept {
    /**
     * 
     * @type {boolean}
     * @memberof TenantPoliciesAccept
     */
    ok: boolean;
    /**
     * Policy version the tenant just accepted
     * @type {string}
     * @memberof TenantPoliciesAccept
     */
    acceptedVersion: string;
    /**
     * Current policy version required by the platform
     * @type {string}
     * @memberof TenantPoliciesAccept
     */
    requiredPolicyVersion: string;
}

/**
 * Check if a given object implements the TenantPoliciesAccept interface.
 */
export function instanceOfTenantPoliciesAccept(value: object): value is TenantPoliciesAccept {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('acceptedVersion' in value) || value['acceptedVersion'] === undefined) return false;
    if (!('requiredPolicyVersion' in value) || value['requiredPolicyVersion'] === undefined) return false;
    return true;
}

export function TenantPoliciesAcceptFromJSON(json: any): TenantPoliciesAccept {
    return TenantPoliciesAcceptFromJSONTyped(json, false);
}

export function TenantPoliciesAcceptFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantPoliciesAccept {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'acceptedVersion': json['acceptedVersion'],
        'requiredPolicyVersion': json['requiredPolicyVersion'],
    };
}

export function TenantPoliciesAcceptToJSON(json: any): TenantPoliciesAccept {
    return TenantPoliciesAcceptToJSONTyped(json, false);
}

export function TenantPoliciesAcceptToJSONTyped(value?: TenantPoliciesAccept | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'acceptedVersion': value['acceptedVersion'],
        'requiredPolicyVersion': value['requiredPolicyVersion'],
    };
}

