/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainStatusEnum } from './DomainStatusEnum';
import {
    DomainStatusEnumFromJSON,
    DomainStatusEnumFromJSONTyped,
    DomainStatusEnumToJSON,
    DomainStatusEnumToJSONTyped,
} from './DomainStatusEnum';
import type { TenantDomainSesStatus } from './TenantDomainSesStatus';
import {
    TenantDomainSesStatusFromJSON,
    TenantDomainSesStatusFromJSONTyped,
    TenantDomainSesStatusToJSON,
    TenantDomainSesStatusToJSONTyped,
} from './TenantDomainSesStatus';

/**
 * 
 * @export
 * @interface TenantDomainCheck
 */
export interface TenantDomainCheck {
    /**
     * 
     * @type {string}
     * @memberof TenantDomainCheck
     */
    domain: string;
    /**
     * 
     * @type {DomainStatusEnum}
     * @memberof TenantDomainCheck
     */
    status: DomainStatusEnum;
    /**
     * 
     * @type {TenantDomainSesStatus}
     * @memberof TenantDomainCheck
     */
    ses: TenantDomainSesStatus;
}



/**
 * Check if a given object implements the TenantDomainCheck interface.
 */
export function instanceOfTenantDomainCheck(value: object): value is TenantDomainCheck {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('ses' in value) || value['ses'] === undefined) return false;
    return true;
}

export function TenantDomainCheckFromJSON(json: any): TenantDomainCheck {
    return TenantDomainCheckFromJSONTyped(json, false);
}

export function TenantDomainCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'status': DomainStatusEnumFromJSON(json['status']),
        'ses': TenantDomainSesStatusFromJSON(json['ses']),
    };
}

export function TenantDomainCheckToJSON(json: any): TenantDomainCheck {
    return TenantDomainCheckToJSONTyped(json, false);
}

export function TenantDomainCheckToJSONTyped(value?: TenantDomainCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'status': DomainStatusEnumToJSON(value['status']),
        'ses': TenantDomainSesStatusToJSON(value['ses']),
    };
}

