/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDomainCreate } from './TenantDomainCreate';
import {
    TenantDomainCreateFromJSON,
    TenantDomainCreateFromJSONTyped,
    TenantDomainCreateToJSON,
    TenantDomainCreateToJSONTyped,
} from './TenantDomainCreate';

/**
 * 
 * @export
 * @interface TenantDomainCreateResponse
 */
export interface TenantDomainCreateResponse {
    /**
     * 
     * @type {TenantDomainCreate}
     * @memberof TenantDomainCreateResponse
     */
    data: TenantDomainCreate;
}

/**
 * Check if a given object implements the TenantDomainCreateResponse interface.
 */
export function instanceOfTenantDomainCreateResponse(value: object): value is TenantDomainCreateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantDomainCreateResponseFromJSON(json: any): TenantDomainCreateResponse {
    return TenantDomainCreateResponseFromJSONTyped(json, false);
}

export function TenantDomainCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantDomainCreateFromJSON(json['data']),
    };
}

export function TenantDomainCreateResponseToJSON(json: any): TenantDomainCreateResponse {
    return TenantDomainCreateResponseToJSONTyped(json, false);
}

export function TenantDomainCreateResponseToJSONTyped(value?: TenantDomainCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantDomainCreateToJSON(value['data']),
    };
}

