/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessage } from './TenantMessage';
import {
    TenantMessageFromJSON,
    TenantMessageFromJSONTyped,
    TenantMessageToJSON,
    TenantMessageToJSONTyped,
} from './TenantMessage';

/**
 * 
 * @export
 * @interface TenantMessageResponse
 */
export interface TenantMessageResponse {
    /**
     * 
     * @type {TenantMessage}
     * @memberof TenantMessageResponse
     */
    data: TenantMessage;
}

/**
 * Check if a given object implements the TenantMessageResponse interface.
 */
export function instanceOfTenantMessageResponse(value: object): value is TenantMessageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantMessageResponseFromJSON(json: any): TenantMessageResponse {
    return TenantMessageResponseFromJSONTyped(json, false);
}

export function TenantMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantMessageFromJSON(json['data']),
    };
}

export function TenantMessageResponseToJSON(json: any): TenantMessageResponse {
    return TenantMessageResponseToJSONTyped(json, false);
}

export function TenantMessageResponseToJSONTyped(value?: TenantMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantMessageToJSON(value['data']),
    };
}

