/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessage } from './TenantMessage';
import {
    TenantMessageFromJSON,
    TenantMessageFromJSONTyped,
    TenantMessageToJSON,
    TenantMessageToJSONTyped,
} from './TenantMessage';

/**
 * 
 * @export
 * @interface TenantMessagesPage
 */
export interface TenantMessagesPage {
    /**
     * 
     * @type {Array<TenantMessage>}
     * @memberof TenantMessagesPage
     */
    items: Array<TenantMessage>;
    /**
     * Opaque pagination cursor for the next page
     * @type {string}
     * @memberof TenantMessagesPage
     */
    cursor: string | null;
}

/**
 * Check if a given object implements the TenantMessagesPage interface.
 */
export function instanceOfTenantMessagesPage(value: object): value is TenantMessagesPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function TenantMessagesPageFromJSON(json: any): TenantMessagesPage {
    return TenantMessagesPageFromJSONTyped(json, false);
}

export function TenantMessagesPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessagesPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TenantMessageFromJSON)),
        'cursor': json['cursor'],
    };
}

export function TenantMessagesPageToJSON(json: any): TenantMessagesPage {
    return TenantMessagesPageToJSONTyped(json, false);
}

export function TenantMessagesPageToJSONTyped(value?: TenantMessagesPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TenantMessageToJSON)),
        'cursor': value['cursor'],
    };
}

