/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TenantMessageInternalEvent } from './TenantMessageInternalEvent';
import {
    instanceOfTenantMessageInternalEvent,
    TenantMessageInternalEventFromJSON,
    TenantMessageInternalEventFromJSONTyped,
    TenantMessageInternalEventToJSON,
} from './TenantMessageInternalEvent';
import type { TenantMessageProviderEvent } from './TenantMessageProviderEvent';
import {
    instanceOfTenantMessageProviderEvent,
    TenantMessageProviderEventFromJSON,
    TenantMessageProviderEventFromJSONTyped,
    TenantMessageProviderEventToJSON,
} from './TenantMessageProviderEvent';

/**
 * @type TenantMessageEvent
 * 
 * @export
 */
export type TenantMessageEvent = TenantMessageInternalEvent | TenantMessageProviderEvent;

export function TenantMessageEventFromJSON(json: any): TenantMessageEvent {
    return TenantMessageEventFromJSONTyped(json, false);
}

export function TenantMessageEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEvent {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTenantMessageInternalEvent(json)) {
        return TenantMessageInternalEventFromJSONTyped(json, true);
    }
    if (instanceOfTenantMessageProviderEvent(json)) {
        return TenantMessageProviderEventFromJSONTyped(json, true);
    }
    return {} as any;
}

export function TenantMessageEventToJSON(json: any): any {
    return TenantMessageEventToJSONTyped(json, false);
}

export function TenantMessageEventToJSONTyped(value?: TenantMessageEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTenantMessageInternalEvent(value)) {
        return TenantMessageInternalEventToJSON(value as TenantMessageInternalEvent);
    }
    if (instanceOfTenantMessageProviderEvent(value)) {
        return TenantMessageProviderEventToJSON(value as TenantMessageProviderEvent);
    }
    return {};
}

