/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CallerTypeEnum } from './CallerTypeEnum';
import {
    CallerTypeEnumFromJSON,
    CallerTypeEnumFromJSONTyped,
    CallerTypeEnumToJSON,
    CallerTypeEnumToJSONTyped,
} from './CallerTypeEnum';
import type { EventGroupEnum } from './EventGroupEnum';
import {
    EventGroupEnumFromJSON,
    EventGroupEnumFromJSONTyped,
    EventGroupEnumToJSON,
    EventGroupEnumToJSONTyped,
} from './EventGroupEnum';
import type { SourceEnum } from './SourceEnum';
import {
    SourceEnumFromJSON,
    SourceEnumFromJSONTyped,
    SourceEnumToJSON,
    SourceEnumToJSONTyped,
} from './SourceEnum';
import type { StageEnum } from './StageEnum';
import {
    StageEnumFromJSON,
    StageEnumFromJSONTyped,
    StageEnumToJSON,
    StageEnumToJSONTyped,
} from './StageEnum';
import type { MessageStatusEnum } from './MessageStatusEnum';
import {
    MessageStatusEnumFromJSON,
    MessageStatusEnumFromJSONTyped,
    MessageStatusEnumToJSON,
    MessageStatusEnumToJSONTyped,
} from './MessageStatusEnum';

/**
 * 
 * @export
 * @interface TenantMessageInternalEvent
 */
export interface TenantMessageInternalEvent {
    /**
     * 
     * @type {StageEnum}
     * @memberof TenantMessageInternalEvent
     */
    stage: StageEnum | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TenantMessageInternalEvent
     */
    detail: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof TenantMessageInternalEvent
     */
    tenantId: string;
    /**
     * 
     * @type {CallerTypeEnum}
     * @memberof TenantMessageInternalEvent
     */
    callerType: CallerTypeEnum;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof TenantMessageInternalEvent
     */
    status: MessageStatusEnum | null;
    /**
     * 
     * @type {SourceEnum}
     * @memberof TenantMessageInternalEvent
     */
    source: SourceEnum;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessageInternalEvent
     */
    createdAtIso: Date;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageInternalEvent
     */
    reason: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageInternalEvent
     */
    requestId: string;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessageInternalEvent
     */
    eventAtIso: Date;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageInternalEvent
     */
    eventType: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageInternalEvent
     */
    tag: string | null;
    /**
     * 
     * @type {EventGroupEnum}
     * @memberof TenantMessageInternalEvent
     */
    eventGroup: EventGroupEnum;
}



/**
 * Check if a given object implements the TenantMessageInternalEvent interface.
 */
export function instanceOfTenantMessageInternalEvent(value: object): value is TenantMessageInternalEvent {
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('callerType' in value) || value['callerType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('createdAtIso' in value) || value['createdAtIso'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('eventAtIso' in value) || value['eventAtIso'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('eventGroup' in value) || value['eventGroup'] === undefined) return false;
    return true;
}

export function TenantMessageInternalEventFromJSON(json: any): TenantMessageInternalEvent {
    return TenantMessageInternalEventFromJSONTyped(json, false);
}

export function TenantMessageInternalEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageInternalEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'stage': StageEnumFromJSON(json['stage']),
        'detail': json['detail'],
        'tenantId': json['tenantId'],
        'callerType': CallerTypeEnumFromJSON(json['callerType']),
        'status': MessageStatusEnumFromJSON(json['status']),
        'source': SourceEnumFromJSON(json['source']),
        'createdAtIso': (new Date(json['createdAtIso'])),
        'reason': json['reason'],
        'requestId': json['requestId'],
        'eventAtIso': (new Date(json['eventAtIso'])),
        'eventType': json['eventType'],
        'tag': json['tag'],
        'eventGroup': EventGroupEnumFromJSON(json['eventGroup']),
    };
}

export function TenantMessageInternalEventToJSON(json: any): TenantMessageInternalEvent {
    return TenantMessageInternalEventToJSONTyped(json, false);
}

export function TenantMessageInternalEventToJSONTyped(value?: TenantMessageInternalEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stage': StageEnumToJSON(value['stage']),
        'detail': value['detail'],
        'tenantId': value['tenantId'],
        'callerType': CallerTypeEnumToJSON(value['callerType']),
        'status': MessageStatusEnumToJSON(value['status']),
        'source': SourceEnumToJSON(value['source']),
        'createdAtIso': value['createdAtIso'].toISOString(),
        'reason': value['reason'],
        'requestId': value['requestId'],
        'eventAtIso': value['eventAtIso'].toISOString(),
        'eventType': value['eventType'],
        'tag': value['tag'],
        'eventGroup': EventGroupEnumToJSON(value['eventGroup']),
    };
}

