/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDomainCheck } from './TenantDomainCheck';
import {
    TenantDomainCheckFromJSON,
    TenantDomainCheckFromJSONTyped,
    TenantDomainCheckToJSON,
    TenantDomainCheckToJSONTyped,
} from './TenantDomainCheck';

/**
 * 
 * @export
 * @interface TenantDomainCheckResponse
 */
export interface TenantDomainCheckResponse {
    /**
     * 
     * @type {TenantDomainCheck}
     * @memberof TenantDomainCheckResponse
     */
    data: TenantDomainCheck;
}

/**
 * Check if a given object implements the TenantDomainCheckResponse interface.
 */
export function instanceOfTenantDomainCheckResponse(value: object): value is TenantDomainCheckResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantDomainCheckResponseFromJSON(json: any): TenantDomainCheckResponse {
    return TenantDomainCheckResponseFromJSONTyped(json, false);
}

export function TenantDomainCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantDomainCheckFromJSON(json['data']),
    };
}

export function TenantDomainCheckResponseToJSON(json: any): TenantDomainCheckResponse {
    return TenantDomainCheckResponseToJSONTyped(json, false);
}

export function TenantDomainCheckResponseToJSONTyped(value?: TenantDomainCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantDomainCheckToJSON(value['data']),
    };
}

