/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantMessageEventDelivery
 */
export interface TenantMessageEventDelivery {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventDelivery
     */
    smtpResponse?: string;
    /**
     * 
     * @type {number}
     * @memberof TenantMessageEventDelivery
     */
    processingTimeMillis?: number;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventDelivery
     */
    reportingMTA?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventDelivery
     */
    remoteMtaIp?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TenantMessageEventDelivery
     */
    recipients?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessageEventDelivery
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the TenantMessageEventDelivery interface.
 */
export function instanceOfTenantMessageEventDelivery(value: object): value is TenantMessageEventDelivery {
    return true;
}

export function TenantMessageEventDeliveryFromJSON(json: any): TenantMessageEventDelivery {
    return TenantMessageEventDeliveryFromJSONTyped(json, false);
}

export function TenantMessageEventDeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEventDelivery {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'smtpResponse': json['smtpResponse'] == null ? undefined : json['smtpResponse'],
        'processingTimeMillis': json['processingTimeMillis'] == null ? undefined : json['processingTimeMillis'],
        'reportingMTA': json['reportingMTA'] == null ? undefined : json['reportingMTA'],
        'remoteMtaIp': json['remoteMtaIp'] == null ? undefined : json['remoteMtaIp'],
        'recipients': json['recipients'] == null ? undefined : json['recipients'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function TenantMessageEventDeliveryToJSON(json: any): TenantMessageEventDelivery {
    return TenantMessageEventDeliveryToJSONTyped(json, false);
}

export function TenantMessageEventDeliveryToJSONTyped(value?: TenantMessageEventDelivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'smtpResponse': value['smtpResponse'],
        'processingTimeMillis': value['processingTimeMillis'],
        'reportingMTA': value['reportingMTA'],
        'remoteMtaIp': value['remoteMtaIp'],
        'recipients': value['recipients'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

