/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantMessageMetaDelivery
 */
export interface TenantMessageMetaDelivery {
    /**
     * 
     * @type {number}
     * @memberof TenantMessageMetaDelivery
     */
    processingTimeMillis: number;
}

/**
 * Check if a given object implements the TenantMessageMetaDelivery interface.
 */
export function instanceOfTenantMessageMetaDelivery(value: object): value is TenantMessageMetaDelivery {
    if (!('processingTimeMillis' in value) || value['processingTimeMillis'] === undefined) return false;
    return true;
}

export function TenantMessageMetaDeliveryFromJSON(json: any): TenantMessageMetaDelivery {
    return TenantMessageMetaDeliveryFromJSONTyped(json, false);
}

export function TenantMessageMetaDeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageMetaDelivery {
    if (json == null) {
        return json;
    }
    return {
        
        'processingTimeMillis': json['processingTimeMillis'],
    };
}

export function TenantMessageMetaDeliveryToJSON(json: any): TenantMessageMetaDelivery {
    return TenantMessageMetaDeliveryToJSONTyped(json, false);
}

export function TenantMessageMetaDeliveryToJSONTyped(value?: TenantMessageMetaDelivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'processingTimeMillis': value['processingTimeMillis'],
    };
}

