/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessageProviderMeta } from './TenantMessageProviderMeta';
import {
    TenantMessageProviderMetaFromJSON,
    TenantMessageProviderMetaFromJSONTyped,
    TenantMessageProviderMetaToJSON,
    TenantMessageProviderMetaToJSONTyped,
} from './TenantMessageProviderMeta';
import type { EventGroupEnum } from './EventGroupEnum';
import {
    EventGroupEnumFromJSON,
    EventGroupEnumFromJSONTyped,
    EventGroupEnumToJSON,
    EventGroupEnumToJSONTyped,
} from './EventGroupEnum';
import type { ProviderEnum } from './ProviderEnum';
import {
    ProviderEnumFromJSON,
    ProviderEnumFromJSONTyped,
    ProviderEnumToJSON,
    ProviderEnumToJSONTyped,
} from './ProviderEnum';
import type { MessageStatusEnum } from './MessageStatusEnum';
import {
    MessageStatusEnumFromJSON,
    MessageStatusEnumFromJSONTyped,
    MessageStatusEnumToJSON,
    MessageStatusEnumToJSONTyped,
} from './MessageStatusEnum';

/**
 * 
 * @export
 * @interface TenantMessageProviderEvent
 */
export interface TenantMessageProviderEvent {
    /**
     * 
     * @type {Date}
     * @memberof TenantMessageProviderEvent
     */
    eventAtIso: Date;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageProviderEvent
     */
    recipient: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageProviderEvent
     */
    providerMessageId: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageProviderEvent
     */
    messageId: string;
    /**
     * 
     * @type {TenantMessageProviderMeta}
     * @memberof TenantMessageProviderEvent
     */
    meta: TenantMessageProviderMeta;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageProviderEvent
     */
    tenantId: string;
    /**
     * Unix timestamp in seconds
     * @type {number}
     * @memberof TenantMessageProviderEvent
     */
    eventAt: number;
    /**
     * 
     * @type {ProviderEnum}
     * @memberof TenantMessageProviderEvent
     */
    provider: ProviderEnum;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof TenantMessageProviderEvent
     */
    eventType: MessageStatusEnum;
    /**
     * 
     * @type {EventGroupEnum}
     * @memberof TenantMessageProviderEvent
     */
    eventGroup: EventGroupEnum;
}



/**
 * Check if a given object implements the TenantMessageProviderEvent interface.
 */
export function instanceOfTenantMessageProviderEvent(value: object): value is TenantMessageProviderEvent {
    if (!('eventAtIso' in value) || value['eventAtIso'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('providerMessageId' in value) || value['providerMessageId'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('eventAt' in value) || value['eventAt'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('eventGroup' in value) || value['eventGroup'] === undefined) return false;
    return true;
}

export function TenantMessageProviderEventFromJSON(json: any): TenantMessageProviderEvent {
    return TenantMessageProviderEventFromJSONTyped(json, false);
}

export function TenantMessageProviderEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageProviderEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'eventAtIso': (new Date(json['eventAtIso'])),
        'recipient': json['recipient'],
        'providerMessageId': json['providerMessageId'],
        'messageId': json['messageId'],
        'meta': TenantMessageProviderMetaFromJSON(json['meta']),
        'tenantId': json['tenantId'],
        'eventAt': json['eventAt'],
        'provider': ProviderEnumFromJSON(json['provider']),
        'eventType': MessageStatusEnumFromJSON(json['eventType']),
        'eventGroup': EventGroupEnumFromJSON(json['eventGroup']),
    };
}

export function TenantMessageProviderEventToJSON(json: any): TenantMessageProviderEvent {
    return TenantMessageProviderEventToJSONTyped(json, false);
}

export function TenantMessageProviderEventToJSONTyped(value?: TenantMessageProviderEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventAtIso': value['eventAtIso'].toISOString(),
        'recipient': value['recipient'],
        'providerMessageId': value['providerMessageId'],
        'messageId': value['messageId'],
        'meta': TenantMessageProviderMetaToJSON(value['meta']),
        'tenantId': value['tenantId'],
        'eventAt': value['eventAt'],
        'provider': ProviderEnumToJSON(value['provider']),
        'eventType': MessageStatusEnumToJSON(value['eventType']),
        'eventGroup': EventGroupEnumToJSON(value['eventGroup']),
    };
}

