/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantPoliciesAccept } from './TenantPoliciesAccept';
import {
    TenantPoliciesAcceptFromJSON,
    TenantPoliciesAcceptFromJSONTyped,
    TenantPoliciesAcceptToJSON,
    TenantPoliciesAcceptToJSONTyped,
} from './TenantPoliciesAccept';

/**
 * 
 * @export
 * @interface TenantPoliciesAcceptResponse
 */
export interface TenantPoliciesAcceptResponse {
    /**
     * 
     * @type {TenantPoliciesAccept}
     * @memberof TenantPoliciesAcceptResponse
     */
    data: TenantPoliciesAccept;
}

/**
 * Check if a given object implements the TenantPoliciesAcceptResponse interface.
 */
export function instanceOfTenantPoliciesAcceptResponse(value: object): value is TenantPoliciesAcceptResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantPoliciesAcceptResponseFromJSON(json: any): TenantPoliciesAcceptResponse {
    return TenantPoliciesAcceptResponseFromJSONTyped(json, false);
}

export function TenantPoliciesAcceptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantPoliciesAcceptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantPoliciesAcceptFromJSON(json['data']),
    };
}

export function TenantPoliciesAcceptResponseToJSON(json: any): TenantPoliciesAcceptResponse {
    return TenantPoliciesAcceptResponseToJSONTyped(json, false);
}

export function TenantPoliciesAcceptResponseToJSONTyped(value?: TenantPoliciesAcceptResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantPoliciesAcceptToJSON(value['data']),
    };
}

