/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessagesPage } from './TenantMessagesPage';
import {
    TenantMessagesPageFromJSON,
    TenantMessagesPageFromJSONTyped,
    TenantMessagesPageToJSON,
    TenantMessagesPageToJSONTyped,
} from './TenantMessagesPage';

/**
 * 
 * @export
 * @interface TenantMessagesResponse
 */
export interface TenantMessagesResponse {
    /**
     * 
     * @type {TenantMessagesPage}
     * @memberof TenantMessagesResponse
     */
    data: TenantMessagesPage;
}

/**
 * Check if a given object implements the TenantMessagesResponse interface.
 */
export function instanceOfTenantMessagesResponse(value: object): value is TenantMessagesResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantMessagesResponseFromJSON(json: any): TenantMessagesResponse {
    return TenantMessagesResponseFromJSONTyped(json, false);
}

export function TenantMessagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantMessagesPageFromJSON(json['data']),
    };
}

export function TenantMessagesResponseToJSON(json: any): TenantMessagesResponse {
    return TenantMessagesResponseToJSONTyped(json, false);
}

export function TenantMessagesResponseToJSONTyped(value?: TenantMessagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantMessagesPageToJSON(value['data']),
    };
}

