/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessageEventHeader } from './TenantMessageEventHeader';
import {
    TenantMessageEventHeaderFromJSON,
    TenantMessageEventHeaderFromJSONTyped,
    TenantMessageEventHeaderToJSON,
    TenantMessageEventHeaderToJSONTyped,
} from './TenantMessageEventHeader';
import type { TenantMessageEventCommonHeaders } from './TenantMessageEventCommonHeaders';
import {
    TenantMessageEventCommonHeadersFromJSON,
    TenantMessageEventCommonHeadersFromJSONTyped,
    TenantMessageEventCommonHeadersToJSON,
    TenantMessageEventCommonHeadersToJSONTyped,
} from './TenantMessageEventCommonHeaders';

/**
 * 
 * @export
 * @interface TenantMessageEventMail
 */
export interface TenantMessageEventMail {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventMail
     */
    sourceArn?: string;
    /**
     * 
     * @type {Array<TenantMessageEventHeader>}
     * @memberof TenantMessageEventMail
     */
    headers?: Array<TenantMessageEventHeader>;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventMail
     */
    sendingAccountId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TenantMessageEventMail
     */
    destination?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof TenantMessageEventMail
     */
    headersTruncated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventMail
     */
    messageId?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventMail
     */
    source?: string;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessageEventMail
     */
    timestamp?: Date;
    /**
     * 
     * @type {TenantMessageEventCommonHeaders}
     * @memberof TenantMessageEventMail
     */
    commonHeaders?: TenantMessageEventCommonHeaders;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof TenantMessageEventMail
     */
    tags?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the TenantMessageEventMail interface.
 */
export function instanceOfTenantMessageEventMail(value: object): value is TenantMessageEventMail {
    return true;
}

export function TenantMessageEventMailFromJSON(json: any): TenantMessageEventMail {
    return TenantMessageEventMailFromJSONTyped(json, false);
}

export function TenantMessageEventMailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEventMail {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'sourceArn': json['sourceArn'] == null ? undefined : json['sourceArn'],
        'headers': json['headers'] == null ? undefined : ((json['headers'] as Array<any>).map(TenantMessageEventHeaderFromJSON)),
        'sendingAccountId': json['sendingAccountId'] == null ? undefined : json['sendingAccountId'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'headersTruncated': json['headersTruncated'] == null ? undefined : json['headersTruncated'],
        'messageId': json['messageId'] == null ? undefined : json['messageId'],
        'source': json['source'] == null ? undefined : json['source'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'commonHeaders': json['commonHeaders'] == null ? undefined : TenantMessageEventCommonHeadersFromJSON(json['commonHeaders']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function TenantMessageEventMailToJSON(json: any): TenantMessageEventMail {
    return TenantMessageEventMailToJSONTyped(json, false);
}

export function TenantMessageEventMailToJSONTyped(value?: TenantMessageEventMail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'sourceArn': value['sourceArn'],
        'headers': value['headers'] == null ? undefined : ((value['headers'] as Array<any>).map(TenantMessageEventHeaderToJSON)),
        'sendingAccountId': value['sendingAccountId'],
        'destination': value['destination'],
        'headersTruncated': value['headersTruncated'],
        'messageId': value['messageId'],
        'source': value['source'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'commonHeaders': TenantMessageEventCommonHeadersToJSON(value['commonHeaders']),
        'tags': value['tags'],
    };
}

