/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CallerTypeEnum } from './CallerTypeEnum';
import {
    CallerTypeEnumFromJSON,
    CallerTypeEnumFromJSONTyped,
    CallerTypeEnumToJSON,
    CallerTypeEnumToJSONTyped,
} from './CallerTypeEnum';
import type { TenantMessageMeta } from './TenantMessageMeta';
import {
    TenantMessageMetaFromJSON,
    TenantMessageMetaFromJSONTyped,
    TenantMessageMetaToJSON,
    TenantMessageMetaToJSONTyped,
} from './TenantMessageMeta';
import type { SourceEnum } from './SourceEnum';
import {
    SourceEnumFromJSON,
    SourceEnumFromJSONTyped,
    SourceEnumToJSON,
    SourceEnumToJSONTyped,
} from './SourceEnum';
import type { StageEnum } from './StageEnum';
import {
    StageEnumFromJSON,
    StageEnumFromJSONTyped,
    StageEnumToJSON,
    StageEnumToJSONTyped,
} from './StageEnum';
import type { MessageStatusEnum } from './MessageStatusEnum';
import {
    MessageStatusEnumFromJSON,
    MessageStatusEnumFromJSONTyped,
    MessageStatusEnumToJSON,
    MessageStatusEnumToJSONTyped,
} from './MessageStatusEnum';

/**
 * 
 * @export
 * @interface TenantMessage
 */
export interface TenantMessage {
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    requestId: string;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof TenantMessage
     */
    status: MessageStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    reason: string | null;
    /**
     * Unix timestamp in seconds
     * @type {number}
     * @memberof TenantMessage
     */
    createdAt: number;
    /**
     * Unix timestamp in seconds
     * @type {number}
     * @memberof TenantMessage
     */
    updatedAt: number;
    /**
     * Unix timestamp in seconds of the latest known event
     * @type {number}
     * @memberof TenantMessage
     */
    lastEventAt: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessage
     */
    createdAtIso: Date;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessage
     */
    updatedAtIso: Date;
    /**
     * 
     * @type {Date}
     * @memberof TenantMessage
     */
    lastEventAtIso: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    sourceIp: string | null;
    /**
     * 
     * @type {StageEnum}
     * @memberof TenantMessage
     */
    stage: StageEnum | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    tag: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    keyId: string | null;
    /**
     * 
     * @type {CallerTypeEnum}
     * @memberof TenantMessage
     */
    callerType: CallerTypeEnum;
    /**
     * 
     * @type {SourceEnum}
     * @memberof TenantMessage
     */
    lastSource: SourceEnum | null;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof TenantMessage
     */
    lastEventType: MessageStatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    sesMessageId: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantMessage
     */
    idempotencyKey: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TenantMessage
     */
    metadata: { [key: string]: any; } | null;
    /**
     * 
     * @type {TenantMessageMeta}
     * @memberof TenantMessage
     */
    meta: TenantMessageMeta | null;
}



/**
 * Check if a given object implements the TenantMessage interface.
 */
export function instanceOfTenantMessage(value: object): value is TenantMessage {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('lastEventAt' in value) || value['lastEventAt'] === undefined) return false;
    if (!('createdAtIso' in value) || value['createdAtIso'] === undefined) return false;
    if (!('updatedAtIso' in value) || value['updatedAtIso'] === undefined) return false;
    if (!('lastEventAtIso' in value) || value['lastEventAtIso'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('sourceIp' in value) || value['sourceIp'] === undefined) return false;
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('keyId' in value) || value['keyId'] === undefined) return false;
    if (!('callerType' in value) || value['callerType'] === undefined) return false;
    if (!('lastSource' in value) || value['lastSource'] === undefined) return false;
    if (!('lastEventType' in value) || value['lastEventType'] === undefined) return false;
    if (!('sesMessageId' in value) || value['sesMessageId'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function TenantMessageFromJSON(json: any): TenantMessage {
    return TenantMessageFromJSONTyped(json, false);
}

export function TenantMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenantId'],
        'requestId': json['requestId'],
        'status': MessageStatusEnumFromJSON(json['status']),
        'reason': json['reason'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'lastEventAt': json['lastEventAt'],
        'createdAtIso': (new Date(json['createdAtIso'])),
        'updatedAtIso': (new Date(json['updatedAtIso'])),
        'lastEventAtIso': (json['lastEventAtIso'] == null ? null : new Date(json['lastEventAtIso'])),
        'to': json['to'],
        'from': json['from'],
        'subject': json['subject'],
        'sourceIp': json['sourceIp'],
        'stage': StageEnumFromJSON(json['stage']),
        'tag': json['tag'],
        'keyId': json['keyId'],
        'callerType': CallerTypeEnumFromJSON(json['callerType']),
        'lastSource': SourceEnumFromJSON(json['lastSource']),
        'lastEventType': MessageStatusEnumFromJSON(json['lastEventType']),
        'sesMessageId': json['sesMessageId'],
        'idempotencyKey': json['idempotencyKey'],
        'metadata': json['metadata'],
        'meta': TenantMessageMetaFromJSON(json['meta']),
    };
}

export function TenantMessageToJSON(json: any): TenantMessage {
    return TenantMessageToJSONTyped(json, false);
}

export function TenantMessageToJSONTyped(value?: TenantMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenantId': value['tenantId'],
        'requestId': value['requestId'],
        'status': MessageStatusEnumToJSON(value['status']),
        'reason': value['reason'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'lastEventAt': value['lastEventAt'],
        'createdAtIso': value['createdAtIso'].toISOString(),
        'updatedAtIso': value['updatedAtIso'].toISOString(),
        'lastEventAtIso': value['lastEventAtIso'] == null ? value['lastEventAtIso'] : value['lastEventAtIso'].toISOString(),
        'to': value['to'],
        'from': value['from'],
        'subject': value['subject'],
        'sourceIp': value['sourceIp'],
        'stage': StageEnumToJSON(value['stage']),
        'tag': value['tag'],
        'keyId': value['keyId'],
        'callerType': CallerTypeEnumToJSON(value['callerType']),
        'lastSource': SourceEnumToJSON(value['lastSource']),
        'lastEventType': MessageStatusEnumToJSON(value['lastEventType']),
        'sesMessageId': value['sesMessageId'],
        'idempotencyKey': value['idempotencyKey'],
        'metadata': value['metadata'],
        'meta': TenantMessageMetaToJSON(value['meta']),
    };
}

