/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantMessageEventCommonHeaders
 */
export interface TenantMessageEventCommonHeaders {
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventCommonHeaders
     */
    messageId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TenantMessageEventCommonHeaders
     */
    from: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TenantMessageEventCommonHeaders
     */
    to: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventCommonHeaders
     */
    subject: string;
}

/**
 * Check if a given object implements the TenantMessageEventCommonHeaders interface.
 */
export function instanceOfTenantMessageEventCommonHeaders(value: object): value is TenantMessageEventCommonHeaders {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function TenantMessageEventCommonHeadersFromJSON(json: any): TenantMessageEventCommonHeaders {
    return TenantMessageEventCommonHeadersFromJSONTyped(json, false);
}

export function TenantMessageEventCommonHeadersFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEventCommonHeaders {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'],
        'from': json['from'],
        'to': json['to'],
        'subject': json['subject'],
    };
}

export function TenantMessageEventCommonHeadersToJSON(json: any): TenantMessageEventCommonHeaders {
    return TenantMessageEventCommonHeadersToJSONTyped(json, false);
}

export function TenantMessageEventCommonHeadersToJSONTyped(value?: TenantMessageEventCommonHeaders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
        'from': value['from'],
        'to': value['to'],
        'subject': value['subject'],
    };
}

