/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantMessageEventHeader
 */
export interface TenantMessageEventHeader {
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventHeader
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TenantMessageEventHeader
     */
    value: string;
}

/**
 * Check if a given object implements the TenantMessageEventHeader interface.
 */
export function instanceOfTenantMessageEventHeader(value: object): value is TenantMessageEventHeader {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TenantMessageEventHeaderFromJSON(json: any): TenantMessageEventHeader {
    return TenantMessageEventHeaderFromJSONTyped(json, false);
}

export function TenantMessageEventHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEventHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function TenantMessageEventHeaderToJSON(json: any): TenantMessageEventHeader {
    return TenantMessageEventHeaderToJSONTyped(json, false);
}

export function TenantMessageEventHeaderToJSONTyped(value?: TenantMessageEventHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

