/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessageEvent } from './TenantMessageEvent';
import {
    TenantMessageEventFromJSON,
    TenantMessageEventFromJSONTyped,
    TenantMessageEventToJSON,
    TenantMessageEventToJSONTyped,
} from './TenantMessageEvent';

/**
 * 
 * @export
 * @interface TenantMessageEventsPage
 */
export interface TenantMessageEventsPage {
    /**
     * 
     * @type {Array<TenantMessageEvent>}
     * @memberof TenantMessageEventsPage
     */
    items: Array<TenantMessageEvent>;
    /**
     * Opaque pagination cursor for the next page
     * @type {string}
     * @memberof TenantMessageEventsPage
     */
    cursor: string | null;
}

/**
 * Check if a given object implements the TenantMessageEventsPage interface.
 */
export function instanceOfTenantMessageEventsPage(value: object): value is TenantMessageEventsPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function TenantMessageEventsPageFromJSON(json: any): TenantMessageEventsPage {
    return TenantMessageEventsPageFromJSONTyped(json, false);
}

export function TenantMessageEventsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEventsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TenantMessageEventFromJSON)),
        'cursor': json['cursor'],
    };
}

export function TenantMessageEventsPageToJSON(json: any): TenantMessageEventsPage {
    return TenantMessageEventsPageToJSONTyped(json, false);
}

export function TenantMessageEventsPageToJSONTyped(value?: TenantMessageEventsPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TenantMessageEventToJSON)),
        'cursor': value['cursor'],
    };
}

