/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantDomainCreateRequest
 */
export interface TenantDomainCreateRequest {
    /**
     * Domain to register for sending
     * @type {string}
     * @memberof TenantDomainCreateRequest
     */
    domain: string;
}

/**
 * Check if a given object implements the TenantDomainCreateRequest interface.
 */
export function instanceOfTenantDomainCreateRequest(value: object): value is TenantDomainCreateRequest {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function TenantDomainCreateRequestFromJSON(json: any): TenantDomainCreateRequest {
    return TenantDomainCreateRequestFromJSONTyped(json, false);
}

export function TenantDomainCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
    };
}

export function TenantDomainCreateRequestToJSON(json: any): TenantDomainCreateRequest {
    return TenantDomainCreateRequestToJSONTyped(json, false);
}

export function TenantDomainCreateRequestToJSONTyped(value?: TenantDomainCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
    };
}

