/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DnsRecordTypeEnum } from './DnsRecordTypeEnum';
import {
    DnsRecordTypeEnumFromJSON,
    DnsRecordTypeEnumFromJSONTyped,
    DnsRecordTypeEnumToJSON,
    DnsRecordTypeEnumToJSONTyped,
} from './DnsRecordTypeEnum';

/**
 * 
 * @export
 * @interface TenantDomainRecord
 */
export interface TenantDomainRecord {
    /**
     * 
     * @type {DnsRecordTypeEnum}
     * @memberof TenantDomainRecord
     */
    type: DnsRecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TenantDomainRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDomainRecord
     */
    value: string;
}



/**
 * Check if a given object implements the TenantDomainRecord interface.
 */
export function instanceOfTenantDomainRecord(value: object): value is TenantDomainRecord {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TenantDomainRecordFromJSON(json: any): TenantDomainRecord {
    return TenantDomainRecordFromJSONTyped(json, false);
}

export function TenantDomainRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'type': DnsRecordTypeEnumFromJSON(json['type']),
        'name': json['name'],
        'value': json['value'],
    };
}

export function TenantDomainRecordToJSON(json: any): TenantDomainRecord {
    return TenantDomainRecordToJSONTyped(json, false);
}

export function TenantDomainRecordToJSONTyped(value?: TenantDomainRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': DnsRecordTypeEnumToJSON(value['type']),
        'name': value['name'],
        'value': value['value'],
    };
}

