/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessageEventMail } from './TenantMessageEventMail';
import {
    TenantMessageEventMailFromJSON,
    TenantMessageEventMailFromJSONTyped,
    TenantMessageEventMailToJSON,
    TenantMessageEventMailToJSONTyped,
} from './TenantMessageEventMail';
import type { TenantMessageEventDelivery } from './TenantMessageEventDelivery';
import {
    TenantMessageEventDeliveryFromJSON,
    TenantMessageEventDeliveryFromJSONTyped,
    TenantMessageEventDeliveryToJSON,
    TenantMessageEventDeliveryToJSONTyped,
} from './TenantMessageEventDelivery';
import type { ProviderEventTypeEnum } from './ProviderEventTypeEnum';
import {
    ProviderEventTypeEnumFromJSON,
    ProviderEventTypeEnumFromJSONTyped,
    ProviderEventTypeEnumToJSON,
    ProviderEventTypeEnumToJSONTyped,
} from './ProviderEventTypeEnum';

/**
 * 
 * @export
 * @interface TenantMessageProviderMeta
 */
export interface TenantMessageProviderMeta {
    [key: string]: any | any;
    /**
     * 
     * @type {TenantMessageEventMail}
     * @memberof TenantMessageProviderMeta
     */
    mail?: TenantMessageEventMail;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TenantMessageProviderMeta
     */
    send?: { [key: string]: any; };
    /**
     * 
     * @type {TenantMessageEventDelivery}
     * @memberof TenantMessageProviderMeta
     */
    delivery?: TenantMessageEventDelivery;
    /**
     * 
     * @type {ProviderEventTypeEnum}
     * @memberof TenantMessageProviderMeta
     */
    providerEventType?: ProviderEventTypeEnum;
}



/**
 * Check if a given object implements the TenantMessageProviderMeta interface.
 */
export function instanceOfTenantMessageProviderMeta(value: object): value is TenantMessageProviderMeta {
    return true;
}

export function TenantMessageProviderMetaFromJSON(json: any): TenantMessageProviderMeta {
    return TenantMessageProviderMetaFromJSONTyped(json, false);
}

export function TenantMessageProviderMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageProviderMeta {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'mail': json['mail'] == null ? undefined : TenantMessageEventMailFromJSON(json['mail']),
        'send': json['send'] == null ? undefined : json['send'],
        'delivery': json['delivery'] == null ? undefined : TenantMessageEventDeliveryFromJSON(json['delivery']),
        'providerEventType': json['providerEventType'] == null ? undefined : ProviderEventTypeEnumFromJSON(json['providerEventType']),
    };
}

export function TenantMessageProviderMetaToJSON(json: any): TenantMessageProviderMeta {
    return TenantMessageProviderMetaToJSONTyped(json, false);
}

export function TenantMessageProviderMetaToJSONTyped(value?: TenantMessageProviderMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'mail': TenantMessageEventMailToJSON(value['mail']),
        'send': value['send'],
        'delivery': TenantMessageEventDeliveryToJSON(value['delivery']),
        'providerEventType': ProviderEventTypeEnumToJSON(value['providerEventType']),
    };
}

