/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDomain } from './TenantDomain';
import {
    TenantDomainFromJSON,
    TenantDomainFromJSONTyped,
    TenantDomainToJSON,
    TenantDomainToJSONTyped,
} from './TenantDomain';

/**
 * 
 * @export
 * @interface TenantDomainsResponse
 */
export interface TenantDomainsResponse {
    /**
     * 
     * @type {Array<TenantDomain>}
     * @memberof TenantDomainsResponse
     */
    data: Array<TenantDomain>;
}

/**
 * Check if a given object implements the TenantDomainsResponse interface.
 */
export function instanceOfTenantDomainsResponse(value: object): value is TenantDomainsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantDomainsResponseFromJSON(json: any): TenantDomainsResponse {
    return TenantDomainsResponseFromJSONTyped(json, false);
}

export function TenantDomainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TenantDomainFromJSON)),
    };
}

export function TenantDomainsResponseToJSON(json: any): TenantDomainsResponse {
    return TenantDomainsResponseToJSONTyped(json, false);
}

export function TenantDomainsResponseToJSONTyped(value?: TenantDomainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TenantDomainToJSON)),
    };
}

