/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainStatusEnum } from './DomainStatusEnum';
import {
    DomainStatusEnumFromJSON,
    DomainStatusEnumFromJSONTyped,
    DomainStatusEnumToJSON,
    DomainStatusEnumToJSONTyped,
} from './DomainStatusEnum';

/**
 * 
 * @export
 * @interface TenantDomainCreate
 */
export interface TenantDomainCreate {
    /**
     * 
     * @type {string}
     * @memberof TenantDomainCreate
     */
    domain: string;
    /**
     * 
     * @type {DomainStatusEnum}
     * @memberof TenantDomainCreate
     */
    status: DomainStatusEnum;
}



/**
 * Check if a given object implements the TenantDomainCreate interface.
 */
export function instanceOfTenantDomainCreate(value: object): value is TenantDomainCreate {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TenantDomainCreateFromJSON(json: any): TenantDomainCreate {
    return TenantDomainCreateFromJSONTyped(json, false);
}

export function TenantDomainCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'status': DomainStatusEnumFromJSON(json['status']),
    };
}

export function TenantDomainCreateToJSON(json: any): TenantDomainCreate {
    return TenantDomainCreateToJSONTyped(json, false);
}

export function TenantDomainCreateToJSONTyped(value?: TenantDomainCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'status': DomainStatusEnumToJSON(value['status']),
    };
}

