/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SesVerificationStatusEnum } from './SesVerificationStatusEnum';
import {
    SesVerificationStatusEnumFromJSON,
    SesVerificationStatusEnumFromJSONTyped,
    SesVerificationStatusEnumToJSON,
    SesVerificationStatusEnumToJSONTyped,
} from './SesVerificationStatusEnum';

/**
 * 
 * @export
 * @interface TenantDomainSesStatus
 */
export interface TenantDomainSesStatus {
    /**
     * 
     * @type {SesVerificationStatusEnum}
     * @memberof TenantDomainSesStatus
     */
    verificationStatus: SesVerificationStatusEnum;
    /**
     * 
     * @type {SesVerificationStatusEnum}
     * @memberof TenantDomainSesStatus
     */
    dkimStatus: SesVerificationStatusEnum;
}



/**
 * Check if a given object implements the TenantDomainSesStatus interface.
 */
export function instanceOfTenantDomainSesStatus(value: object): value is TenantDomainSesStatus {
    if (!('verificationStatus' in value) || value['verificationStatus'] === undefined) return false;
    if (!('dkimStatus' in value) || value['dkimStatus'] === undefined) return false;
    return true;
}

export function TenantDomainSesStatusFromJSON(json: any): TenantDomainSesStatus {
    return TenantDomainSesStatusFromJSONTyped(json, false);
}

export function TenantDomainSesStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainSesStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationStatus': SesVerificationStatusEnumFromJSON(json['verificationStatus']),
        'dkimStatus': SesVerificationStatusEnumFromJSON(json['dkimStatus']),
    };
}

export function TenantDomainSesStatusToJSON(json: any): TenantDomainSesStatus {
    return TenantDomainSesStatusToJSONTyped(json, false);
}

export function TenantDomainSesStatusToJSONTyped(value?: TenantDomainSesStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verificationStatus': SesVerificationStatusEnumToJSON(value['verificationStatus']),
        'dkimStatus': SesVerificationStatusEnumToJSON(value['dkimStatus']),
    };
}

