/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessageEventsPage } from './TenantMessageEventsPage';
import {
    TenantMessageEventsPageFromJSON,
    TenantMessageEventsPageFromJSONTyped,
    TenantMessageEventsPageToJSON,
    TenantMessageEventsPageToJSONTyped,
} from './TenantMessageEventsPage';

/**
 * 
 * @export
 * @interface TenantMessageEventsResponse
 */
export interface TenantMessageEventsResponse {
    /**
     * 
     * @type {TenantMessageEventsPage}
     * @memberof TenantMessageEventsResponse
     */
    data: TenantMessageEventsPage;
}

/**
 * Check if a given object implements the TenantMessageEventsResponse interface.
 */
export function instanceOfTenantMessageEventsResponse(value: object): value is TenantMessageEventsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TenantMessageEventsResponseFromJSON(json: any): TenantMessageEventsResponse {
    return TenantMessageEventsResponseFromJSONTyped(json, false);
}

export function TenantMessageEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TenantMessageEventsPageFromJSON(json['data']),
    };
}

export function TenantMessageEventsResponseToJSON(json: any): TenantMessageEventsResponse {
    return TenantMessageEventsResponseToJSONTyped(json, false);
}

export function TenantMessageEventsResponseToJSONTyped(value?: TenantMessageEventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TenantMessageEventsPageToJSON(value['data']),
    };
}

