/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantMessageMetaDelivery } from './TenantMessageMetaDelivery';
import {
    TenantMessageMetaDeliveryFromJSON,
    TenantMessageMetaDeliveryFromJSONTyped,
    TenantMessageMetaDeliveryToJSON,
    TenantMessageMetaDeliveryToJSONTyped,
} from './TenantMessageMetaDelivery';

/**
 * 
 * @export
 * @interface TenantMessageMeta
 */
export interface TenantMessageMeta {
    /**
     * 
     * @type {TenantMessageMetaDelivery}
     * @memberof TenantMessageMeta
     */
    delivery: TenantMessageMetaDelivery;
}

/**
 * Check if a given object implements the TenantMessageMeta interface.
 */
export function instanceOfTenantMessageMeta(value: object): value is TenantMessageMeta {
    if (!('delivery' in value) || value['delivery'] === undefined) return false;
    return true;
}

export function TenantMessageMetaFromJSON(json: any): TenantMessageMeta {
    return TenantMessageMetaFromJSONTyped(json, false);
}

export function TenantMessageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantMessageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'delivery': TenantMessageMetaDeliveryFromJSON(json['delivery']),
    };
}

export function TenantMessageMetaToJSON(json: any): TenantMessageMeta {
    return TenantMessageMetaToJSONTyped(json, false);
}

export function TenantMessageMetaToJSONTyped(value?: TenantMessageMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delivery': TenantMessageMetaDeliveryToJSON(value['delivery']),
    };
}

