/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantDomainRecord } from './TenantDomainRecord';
import {
    TenantDomainRecordFromJSON,
    TenantDomainRecordFromJSONTyped,
    TenantDomainRecordToJSON,
    TenantDomainRecordToJSONTyped,
} from './TenantDomainRecord';
import type { DomainStatusEnum } from './DomainStatusEnum';
import {
    DomainStatusEnumFromJSON,
    DomainStatusEnumFromJSONTyped,
    DomainStatusEnumToJSON,
    DomainStatusEnumToJSONTyped,
} from './DomainStatusEnum';
import type { TenantDomainSesStatus } from './TenantDomainSesStatus';
import {
    TenantDomainSesStatusFromJSON,
    TenantDomainSesStatusFromJSONTyped,
    TenantDomainSesStatusToJSON,
    TenantDomainSesStatusToJSONTyped,
} from './TenantDomainSesStatus';

/**
 * 
 * @export
 * @interface TenantDomainDetail
 */
export interface TenantDomainDetail {
    /**
     * 
     * @type {string}
     * @memberof TenantDomainDetail
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof TenantDomainDetail
     */
    mailFromDomain: string;
    /**
     * 
     * @type {DomainStatusEnum}
     * @memberof TenantDomainDetail
     */
    status: DomainStatusEnum;
    /**
     * 
     * @type {TenantDomainSesStatus}
     * @memberof TenantDomainDetail
     */
    ses: TenantDomainSesStatus;
    /**
     * 
     * @type {Array<TenantDomainRecord>}
     * @memberof TenantDomainDetail
     */
    records: Array<TenantDomainRecord>;
}



/**
 * Check if a given object implements the TenantDomainDetail interface.
 */
export function instanceOfTenantDomainDetail(value: object): value is TenantDomainDetail {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('mailFromDomain' in value) || value['mailFromDomain'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('ses' in value) || value['ses'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function TenantDomainDetailFromJSON(json: any): TenantDomainDetail {
    return TenantDomainDetailFromJSONTyped(json, false);
}

export function TenantDomainDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomainDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'mailFromDomain': json['mailFromDomain'],
        'status': DomainStatusEnumFromJSON(json['status']),
        'ses': TenantDomainSesStatusFromJSON(json['ses']),
        'records': ((json['records'] as Array<any>).map(TenantDomainRecordFromJSON)),
    };
}

export function TenantDomainDetailToJSON(json: any): TenantDomainDetail {
    return TenantDomainDetailToJSONTyped(json, false);
}

export function TenantDomainDetailToJSONTyped(value?: TenantDomainDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'mailFromDomain': value['mailFromDomain'],
        'status': DomainStatusEnumToJSON(value['status']),
        'ses': TenantDomainSesStatusToJSON(value['ses']),
        'records': ((value['records'] as Array<any>).map(TenantDomainRecordToJSON)),
    };
}

