/* tslint:disable */
/* eslint-disable */
/**
 * Dependal API
 * Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@dependal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainStatusEnum } from './DomainStatusEnum';
import {
    DomainStatusEnumFromJSON,
    DomainStatusEnumFromJSONTyped,
    DomainStatusEnumToJSON,
    DomainStatusEnumToJSONTyped,
} from './DomainStatusEnum';

/**
 * 
 * @export
 * @interface TenantDomain
 */
export interface TenantDomain {
    /**
     * 
     * @type {string}
     * @memberof TenantDomain
     */
    domain: string;
    /**
     * 
     * @type {DomainStatusEnum}
     * @memberof TenantDomain
     */
    status: DomainStatusEnum;
    /**
     * Unix timestamp in seconds
     * @type {number}
     * @memberof TenantDomain
     */
    createdAt: number;
    /**
     * Unix timestamp in seconds when the domain was verified
     * @type {number}
     * @memberof TenantDomain
     */
    verifiedAt: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TenantDomain
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the TenantDomain interface.
 */
export function instanceOfTenantDomain(value: object): value is TenantDomain {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('verifiedAt' in value) || value['verifiedAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TenantDomainFromJSON(json: any): TenantDomain {
    return TenantDomainFromJSONTyped(json, false);
}

export function TenantDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'status': DomainStatusEnumFromJSON(json['status']),
        'createdAt': json['createdAt'],
        'verifiedAt': json['verifiedAt'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TenantDomainToJSON(json: any): TenantDomain {
    return TenantDomainToJSONTyped(json, false);
}

export function TenantDomainToJSONTyped(value?: TenantDomain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'status': DomainStatusEnumToJSON(value['status']),
        'createdAt': value['createdAt'],
        'verifiedAt': value['verifiedAt'],
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

